### ISSUE TITLE
Add Dark Mode

### ISSUE THREAD

**Issue by joshualauw** [joshualauw/portfolio#4]

**Comment by aman-s1** [comment]
I would like to try this . Can you assign this to me?

**Comment by joshualauw** [comment]
sure

**Comment by aman-s1** [comment]
Bro give me permissions to deploy my branch in your repo.

**Comment by aman-s1** [comment]
I have created a PR , please look at it. https://github.com/joshualauw/portfolio/pull/5

**Comment by joshualauw** [comment]
it works, but the spacing messes up a bit. I will fix it myself. Thank you anyways
